version: "3.3"

services:
    food-app:
        build:
            context: ./../
            dockerfile: ./docker/Dockerfile

        volumes:
            - ./../:/app
            - /app/node_modules

        ports:
            - '8080:8080'

        environment:
            - CHOKIDAR_USEPOLLING=true

    api-app:
        build:
            context: ./../src/api
            dockerfile: Dockerfile

        working_dir: /app

        ports:
            - "8000:8000"

        volumes:
            - ./../src/api:/app
            - /app/node_modules
