version: "3.3"

services:
    food-app:

        build:
            context: ./../
            dockerfile: ./docker/Dockerfile

        volumes:
            - ./../:/app
            - ./../api:/app/api
            - /app/node_modules
            - /app/api/node_modules

        ports:
            - '8080:8080'
            - '8000:8000'

        environment:
            - CHOKIDAR_USEPOLLING=true
