version: "3.3"

services:

    food-app:
        build:
            context: .
            dockerfile: Dockerfile-prod

        volumes:
            - '/app/node_modules'

        ports:
            - '1337:80'





    api-app:
        build:
            context: ./src/api
            dockerfile: Dockerfile

        ports:
            - "8000:8000"

        volumes:
            - ./src/api:/var/www/html/app
