# build environment
FROM node:lts-alpine as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
COPY . ./
RUN npm install
COPY . ./
RUN npm run build


# production environment
FROM nginx:stable-alpine

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/index.html /usr/share/nginx/html
COPY --from=build /app/favicon.png /usr/share/nginx/html
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
